"""Add darkmode to user

Revision ID: 22c4d8d756f7
Revises: 2dbfa7f66637
Create Date: 2026-05-13 11:47:11.711775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c4d8d756f7'
down_revision = '2dbfa7f66637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_sessions')
    op.add_column('users', sa.Column('darkmode', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessions',
    sa.Column('quiz_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=False),
    sa.Column('source_session_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.Column('is_saved', sa.BOOLEAN(), nullable=False),
    sa.Column('is_retake', sa.BOOLEAN(), nullable=False),
    sa.Column('taken_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['quiz_sessions.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    # ### end Alembic commands ###
