"""Add darkmode to user

Revision ID: 22c4d8d756f7
Revises: 2dbfa7f66637
Create Date: 2026-05-13 11:47:11.711775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c4d8d756f7'
down_revision = '2dbfa7f66637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('darkmode', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'darkmode')
    # ### end Alembic commands ###
