"""Renamed 'quiz_sessions' table to just quizzes. Removed all functionality for quiz retakes. Updated all references to quizzes in notes and quiz_questions. Further general reworks of quizzes and quiz_questions to fit into current specifications.

Revision ID: 79cad5504af4
Revises: 1c441ecec7e9
Create Date: 2026-05-08 18:43:43.465578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216fe5fa8f37'
down_revision = '1c441ecec7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new `quizzes` table and preserve data from `quiz_sessions`.
    op.create_table('quizzes',
        sa.Column('quiz_id', sa.Integer(), nullable=False),
        sa.Column('note_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('total_questions', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('total_correct', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_accessed', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name='fk_quizzes_note_id_notes'),
        sa.PrimaryKeyConstraint('quiz_id')
    )

    # Migrate existing data from quiz_sessions -> quizzes
    # Map: total_questions <- total, total_correct <- score
    op.execute("""
    INSERT INTO quizzes (quiz_id, note_id, name, total_questions, total_correct, created_at, last_accessed)
    SELECT quiz_id, note_id, '', COALESCE(total, 0), COALESCE(score, 0),
           COALESCE(taken_at, CURRENT_TIMESTAMP), COALESCE(taken_at, CURRENT_TIMESTAMP)
    FROM quiz_sessions
    """)

    # Add new columns to quiz_questions as nullable
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=256), nullable=True))

    # Populate new columns from old columns
    op.execute("""
    UPDATE quiz_questions
    SET quiz_id = session_id,
        correct_answer = COALESCE(correct_option, '')
    WHERE session_id IS NOT NULL
    """)

    # Drop old columns (which implicitly drops their FKs) and create new FK
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('is_correct')
        batch_op.drop_column('correct_option')
        # Now create the FK to new quizzes table with explicit name
        batch_op.create_foreign_key('fk_quiz_questions_quiz_id_quizzes', 'quizzes', ['quiz_id'], ['quiz_id'])
        # Make new columns non-nullable
        batch_op.alter_column('quiz_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('correct_answer', existing_type=sa.String(length=256), nullable=False)

    # Finally remove the old quiz_sessions table
    op.drop_table('quiz_sessions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back old quiz_questions columns as nullable
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('correct_option', sa.VARCHAR(length=256), nullable=True))

    # Populate old columns from new columns
    op.execute("""
    UPDATE quiz_questions
    SET session_id = quiz_id,
        correct_option = correct_answer
    WHERE quiz_id IS NOT NULL
    """)

    # Drop new columns and create FK to quiz_sessions
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_questions_quiz_id_quizzes', type_='foreignkey')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('quiz_id')
        # Create FK to quiz_sessions (will exist after we recreate it below)
        batch_op.create_foreign_key('fk_quiz_questions_session_id_quiz_sessions', 'quiz_sessions', ['session_id'], ['quiz_id'])
        # Make old columns non-nullable
        batch_op.alter_column('session_id', existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column('correct_option', existing_type=sa.VARCHAR(length=256), nullable=False)

    # Recreate quiz_sessions and migrate data back from quizzes
    op.create_table('quiz_sessions',
        sa.Column('quiz_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=True),
        sa.Column('note_id', sa.INTEGER(), nullable=False),
        sa.Column('source_session_id', sa.INTEGER(), nullable=True),
        sa.Column('score', sa.INTEGER(), nullable=False),
        sa.Column('total', sa.INTEGER(), nullable=False),
        sa.Column('is_saved', sa.BOOLEAN(), nullable=False),
        sa.Column('is_retake', sa.BOOLEAN(), nullable=False),
        sa.Column('taken_at', sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], name='fk_quiz_sessions_note_id_notes'),
        sa.ForeignKeyConstraint(['source_session_id'], ['quiz_sessions.quiz_id'], name='fk_quiz_sessions_source_session_id_quiz_sessions'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_quiz_sessions_user_id_users'),
        sa.PrimaryKeyConstraint('quiz_id')
    )

    # Migrate data back: map total_questions -> total, total_correct -> score
    op.execute("""
    INSERT INTO quiz_sessions (quiz_id, user_id, note_id, source_session_id, score, total, is_saved, is_retake, taken_at)
    SELECT quiz_id, NULL, note_id, NULL, COALESCE(total_correct,0), COALESCE(total_questions,0), 0, 0, created_at
    FROM quizzes
    """)

    # Drop quizzes table
    op.drop_table('quizzes')
    # ### end Alembic commands ###
