"""Added new is_completed attribute to Quiz, to track completion status of quizzes

Revision ID: d5ca6f9b0d2e
Revises: 216fe5fa8f37
Create Date: 2026-05-09 20:00:54.708036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ca6f9b0d2e'
down_revision = '216fe5fa8f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=False,server_default=sa.false()))

    # Reserve db default control to the ORM
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('is_completed', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
